name = "my-geobase"
compatibility_date = "2026-05-12"
pages_build_output_dir = "out"

[vars]
APP_ORIGIN = "https://geobase.online"
CREEM_API_BASE = "https://api.creem.io"
CREEM_ENV = "live"

[[kv_namespaces]]
binding = "ANALYTICS_KV"
id = "be10820b635042468a0c7776320a682e"
